### ISSUE TITLE
getConnectionResolver Improvements

### ISSUE THREAD

**Issue by smartprix** [smartprix/gqutils#1]
- [ ] totalCount should use nested query
- [ ] totalCount should remove all order by statements (look into objection native API, eg. `resultSize`)
- [ ] totalCount should remove `runAfter` and maybe `runBefore`

**Comment by rohit-gohri** [comment]
- [x] `last` paging argument also doesn't work with `getConnectionResolver`

```
The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:208:11)
    at getIdFromCursor (/home/smpx-170l/projects/smartprix/node_modules/gqutils/dist/connection.js:13:24)
    at getPagingParams (/home/smpx-170l/projects/smartprix/node_modules/gqutils/dist/connection.js:37:18)
    at getConnectionResolver (/home/smpx-170l/projects/smartprix/node_modules/gqutils/dist/connection.js:85:7)
    at categories (/home/smpx-170l/projects/smartprix/src/lib/Category/resolvers.js:71:22)
    at /home/smpx-170l/projects/smartprix/node_modules/graphql-tools/src/makeExecutableSchema.ts:102:20
    at /home/smpx-170l/projects/smartprix/node_modules/graphql-tools/src/generate/decorateWithLogger.ts:32:22
    at resolveFieldValueOrError (/home/smpx-170l/projects/smartprix/node_modules/graphql/execution/execute.js:479:18)
    at resolveField (/home/smpx-170l/projects/smartprix/node_modules/graphql/execution/execute.js:446:16)
    at executeFields (/home/smpx-170l/projects/smartprix/node_modules/graphql/execution/execute.js:293:18)
    at executeOperation (/home/smpx-170l/projects/smartprix/node_modules/graphql/execution/execute.js:237:122)
    at executeImpl (/home/smpx-170l/projects/smartprix/node_modules/graphql/execution/execute.js:85:14)
    at Object.execute (/home/smpx-170l/projects/smartprix/node_modules/graphql/execution/execute.js:62:229)
    at doRunQuery (/home/smpx-170l/projects/smartprix/node_modules/apollo-server-core/src/runQuery.ts:197:7)
    at /home/smpx-170l/projects/smartprix/node_modules/apollo-server-core/src/runQuery.ts:80:39
```

**Comment by rohit-gohri** [comment]
- [ ] `hasNextPage` should also use `totalCount` result instead of just checking edgeCount and limit. Currently it returns wrong results when limit is set to totalCount

**Comment by hit12369** [comment]
`totalCount` can be very expensive. Checking `edgeCount` is just a way to have a no cost `hasNextPage`, this might be wrong in the last page of results, but I don't think it's that big of an issue (next page will have empty results and `hasNextPage` will be false).

**Comment by rohit-gohri** [comment]
We can at least do something like cache`totalCount` (like `nodes` are) and use it if both `totalCount` and `hasNextPage` are queried.
Otherwise this should be mentioned in the readme or in the description of the `hasNextPage` field.
